version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data # Updated volume mount
    user: "1000:1000" # This ensures proper permissions
